// Generated by https://quicktype.io

//step1: install paste json to code
//step2: create typescript file with corret name
//strp3: go to json data and copy
//step4: ctrl shift p
//step5: give model name
export interface MovieCard {
    id:        number;
    title:     string;
    posterUrl: string;
}


